//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArianaRiseConstructionCompany.Models.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArianaRiseCCEntities : DbContext
    {
        public ArianaRiseCCEntities()
            : base("name=ArianaRiseCCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_aradajat> tbl_aradajat { get; set; }
        public virtual DbSet<tbl_da_kar_da_parmakhtag_jadwal> tbl_da_kar_da_parmakhtag_jadwal { get; set; }
        public virtual DbSet<tbl_da_nan_wraze_karz> tbl_da_nan_wraze_karz { get; set; }
        public virtual DbSet<tbl_markaze_daftar_ta_peshnehadat> tbl_markaze_daftar_ta_peshnehadat { get; set; }
        public virtual DbSet<tbl_mashenare_karaya> tbl_mashenare_karaya { get; set; }
        public virtual DbSet<tbl_masrafe_motafaraqa_mawad> tbl_masrafe_motafaraqa_mawad { get; set; }
        public virtual DbSet<tbl_motar_tarmim_aw_normasayal> tbl_motar_tarmim_aw_normasayal { get; set; }
        public virtual DbSet<tbl_sahawe_daftar_karaya_aw_mashat> tbl_sahawe_daftar_karaya_aw_mashat { get; set; }
        public virtual DbSet<tbl_sakhtamane_mawad> tbl_sakhtamane_mawad { get; set; }
        public virtual DbSet<tbl_shawahed> tbl_shawahed { get; set; }
        public virtual DbSet<tbl_karaya> tbl_karaya { get; set; }
        public virtual DbSet<tbl_projects> tbl_projects { get; set; }
    }
}
